### ISSUE TITLE
AdSettings could not be found.

### ISSUE THREAD

**Issue by JoeQ92** [digicrafts/Advertising-ANE#11]
I get the following error in flash develop:

[Fault] exception, information=VerifyError: Error #1014: Class digicrafts.extensions.core::AdSettings could not be found.

I've added the .swc file to my lib folder, added it to the library and selected external library option as said in the ReadMe.

I have imported the libraries as follows:

import digicrafts.extensions.Advertising;
import digicrafts.extensions.core.AdSettings;
import digicrafts.extensions.data._;
import digicrafts.extensions.adapter._;
import digicrafts.extensions.events.*;

Yet I still get this error. Why is this?

Thanks

**Comment by tsangwailam** [comment]
@JoeQ92 Which IDE and OS are you working with?

**Comment by JoeQ92** [comment]
FlashDevelop and Windows 7

**Comment by tsangwailam** [comment]
Are you using the newest version in the master branch?

**Comment by JoeQ92** [comment]
Yes, I believe so.

**Comment by tsangwailam** [comment]
Did you use any ANE before? And they working?

Since i am not familiarise with FlashDevelop, don't know if you are setup correctly.

**Comment by JoeQ92** [comment]
Yes I've used other ANE's before and they do work

**Comment by tsangwailam** [comment]
Did you have a sample i can test with?

**Comment by JoeQ92** [comment]
A sample of what?

**Comment by tsangwailam** [comment]
Your running example with the error.

But i believe it may be something wrong with the setup. Did you try clean the cache? And did you update the app xml.

**Comment by JoeQ92** [comment]
I used the code given in readme:

package Managers 
{
    import digicrafts.extensions.Advertising;
    import digicrafts.extensions.core.AdSettings;
    import digicrafts.extensions.data._;
    import digicrafts.extensions.adapter._;
    import digicrafts.extensions.events.*;

```
public class AdManager 
{

    public function AdManager() 
    {
        // Create a setting instance for the banner         
        var settings:AdSettings= new AdSettings();

        // Manual create adapter
        // AdMob
        var adMob:AdMobAdapter=new AdMobAdapter('AD-UNIT-ID');
        // Amazon
        var amazon:AmazonAdapter=new AmazonAdapter('APP_ID');        
        // iAd
        var iAd:IAdAdapter=new IAdAdapter();
        // Backfill
        // * Remember to include banner images when you packaging the app
        var backfill:BackFillAdapter=new BackFillAdapter('http://www.google.com');
        backfill.interstitial="BANNER.png";
        backfill.banner="BANNER.png";
        backfill.full_banner="FULL_BANNER.png";
        backfill.leaderboard="LEADERBOARD.png";
        backfill.medium_rectangle="MEDIUM_RECTANGLE.png";

        // Add the adapter to the settings
        settings.add(adMob,2);
        settings.add(amazon,1);
        settings.add(iAd,3);
        settings.add(backfill, 4);

        Advertising.testMode = true;
```

Advertising.getBanner('BANNER_1',AdSize.BANNER,settings).show(AdPosition.BOTTOM,30);

```
    }

}
```

}   

I get the error:
[Fault] exception, information=VerifyError: Error #1014: Class digicrafts.extensions.core::AdSettings could not be found.

**Comment by tsangwailam** [comment]
You may try use a very simple code to verify if you install the ANE correctly.

``` javascript
package Managers 
{
import digicrafts.extensions.Advertising;

public class AdManager 
{
    public function AdManager() 
    {
         trace('Advertising.isSupported()=',Advertising.isSupported());
    }
}
}
```

If this code don't work means the setup have problem, try delete the swc and extract it from the .ane to your library path.

**Comment by JoeQ92** [comment]
Got this error:

[Fault] exception, information=ReferenceError: Error #1065: Variable digicrafts.extensions::Advertising is not defined.

**Comment by JoeQ92** [comment]
using your code above

**Comment by tsangwailam** [comment]
@JoeQ92 So, you may delete the library and install again. I read before someone use FlashDevelop with ANE need to delete some cache.

**Comment by JoeQ92** [comment]
I've tried deleting the library and re-adding it as well as cleaning the project. Still doesn't work. I've followed these instructions in the readme but with "advertising.swc":

Copy the Mopub.swc file to your project folder.
In the explorer panel, right click the .swc and select Add to Library.
Right-click the swc file in the explorer, choose Options, and select External Library

**Comment by tsangwailam** [comment]
You can try follow this tutorial to setup ANE again.

https://fermmm.wordpress.com/2014/01/04/working-tutorial-to-install-air-native-extensions-in-flash-develop-4-windows-desktop-project/

**Comment by JoeQ92** [comment]
I got it working using the ANE instead of the SWC by following the tutorial posted.

Thanks for your help mate.

**Comment by tsangwailam** [comment]
Thanks you testing.
