### ISSUE TITLE
Unable to load ane/swc in Flash cs6

### ISSUE THREAD

**Issue by goshdarn** [digicrafts/Advertising-ANE#16]
I have gone through the steps as shown in the read me.
1. Added the relevant tags to app xml.
2. Added ane to Flash in the library path.
It doesn't compile however and throws the error ' Unable to load ane'.

I tried with the swc but same result ie  ' Unable to load swc'.

I then replaced the dx.jar but the same thing happened.

Then I tried to check out the classes inside the ane and swc through Flash Develop but it read- 
' Cannot find central directory'.

I have only added the ane(31 kb) and swc(29kb) to the extensionDirectory of my project. Is there any other file that needs to be added to the extensions directory? 

There is a huge 80 mb ane file in the master directory. I tried with that too but Flash crashed as soon as I tried to add it to the library path.

Is there anything else I can do?

Thanks for your time.

**Comment by goshdarn** [comment]
I have successfully compiled with the swc. Now while packaging using adt I get the following errors.

Resource values ---common_strings xml has been skipped because of mismatch with supported languages information in app descriptor.

**Comment by goshdarn** [comment]
Got it to package by deleting most of the strings xml from the resources.

**Comment by hl78** [comment]
Greetings,
I'm trying to use the digicrafts ane in Flash CS6, and having this problem
Access of undefined property AdInterstitial

since you solved your problem, can you please tell me how..or maybe send me a simple sample fla file
Thank you a lot
