### ISSUE TITLE
Error - missing required architecture arm64

### ISSUE THREAD

**Issue by zaidman** [digicrafts/Advertising-ANE#9]
Hi,

Using FlashDevelop, AIR SDK 16.0, while packaging for iOS, got the following error:

ld: missing required architecture arm64 in file C:\Users\XXXX\AppData\Local\Temp\0b8932e3-cb26-4014-941c-2261b4e4b39f/SpeechKit.framework/SpeechKit (3 slices) for architecture arm64
Compilation failed while executing : ld64

**Comment by tsangwailam** [comment]
You can try clone the repo and use that version. The zip version didn't updated yet. Will be update in a few days.
